dist: xenial
sudo: required
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

language: python
cache: pip

notifications:
  email: false

env:
  - H5PY_VERSION="==2.5" EXTRA_PACKAGES="libquadmath0"
  - H5PY_VERSION="==2.6" EXTRA_PACKAGES="libquadmath0"
  - H5PY_VERSION="==2.7" EXTRA_PACKAGES="libquadmath0"
  - H5PY_VERSION="==2.8" EXTRA_PACKAGES="libquadmath0"
  - H5PY_VERSION="==2.9" EXTRA_PACKAGES="libquadmath0"
  - H5PY_VERSION="" EXTRA_PACKAGES="libquadmath0"

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

jobs:
  include:
    - python: "3.8"
      env: H5PY_VERSION="" EXTRA_PACKAGES=""
      arch: arm64
    - python: "3.8"
      env: H5PY_VERSION="" EXTRA_PACKAGES=""
      arch: ppc64le
    - python: "3.8"
      env: H5PY_VERSION="" EXTRA_PACKAGES=""
      arch: s390x

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc libhdf5-serial-dev libblas-dev liblapack-dev libatlas-dev libatlas-base-dev $EXTRA_PACKAGES

# command to install dependencies
#
# Seem to need newer Numpy and Cython as well.
install:
  - pip install -U numpy Cython
  - pip install h5py$H5PY_VERSION
  - pip install -r requirements_tests.txt
  - pip install -e examples/example_hdf5storage_marshaller_plugin

# command to run tests
script: nosetests
