dist: focal
arch:
  - amd64
addons:
  apt:
    update: true
    packages:
      - gcc
      - libhdf5-serial-dev
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - libquadmath0

language: python
cache: pip

notifications:
  email: false

env:
  - H5PY_VERSION="==2.6"
  - H5PY_VERSION="==2.8"
  - H5PY_VERSION="==2.10"

python:
  - "3.5"
  - "3.7"
  - "3.9"

jobs:
  include:
    - python: "3.9"
      env: H5PY_VERSION="==2.10"
      arch: ppc64le

before_install:
  - python -m pip install --upgrade pip

# command to install dependencies
#
# Seem to need newer Numpy and Cython as well.
install:
  - pip install -U numpy Cython
  - pip install h5py$H5PY_VERSION
  - pip install -r requirements_tests.txt
  - pip install .
  - pip install -e examples/example_hdf5storage_marshaller_plugin

# command to run tests
script: pytest
